library:
  log:
    format: text
    level: info
    caller: false
genCode:
  upstream:
    contextTimeout: 120s
    http:
      basePath: /
      readTimeout: 120s
      writeTimeout: 120s
      common:
        hostName: ""
        port: 8080
  downstream:
    contextTimeout: 2000s
    up:
      serviceURL: https://api.up.com.au/api/v1
      clientTimeout: 59s
